version: '3.8'

services:
  file_manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_manager

    volumes:
      - ./file_manager:/home/ctfuser/file_manager:ro
      - ./flag.txt:/flag.txt:ro

    env_file:
      - .env

    ports:
      - "7331:7331"

    command: >
      socat TCP-LISTEN:7331,reuseaddr,fork EXEC:"timeout 300 /home/ctfuser/file_manager",stderr

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped